2022-06-06 18:27:25,158 ERROR: Exception on /explore [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 128, in explore
    return render_template('index.html', title='Explore', posts=posts.items)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Python\projects\CoreCracker\app\templates\base.html", line 40, in top-level template code
    {% block content %}
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 20, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-06-06 18:27:26,023 ERROR: Exception on /explore [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 128, in explore
    return render_template('index.html', title='Explore', posts=posts.items)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Python\projects\CoreCracker\app\templates\base.html", line 40, in top-level template code
    {% block content %}
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 20, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-06-06 18:27:42,998 INFO: Microblog startup [in C:\Python\projects\CoreCracker\app\__init__.py:77]
2022-06-06 22:06:36,458 INFO: Microblog startup [in C:\Python\projects\CoreCracker\app\__init__.py:77]
2022-06-06 22:12:48,846 INFO: Microblog startup [in C:\Python\projects\CoreCracker\app\__init__.py:77]
2022-06-07 09:51:41,940 INFO: Microblog startup [in C:\Python\projects\CoreCracker\app\__init__.py:77]
2022-06-07 09:52:48,512 ERROR: Exception on /user/bob [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'user' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-07 09:52:50,570 ERROR: Exception on /user/bob [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'user' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-07 09:55:26,677 ERROR: Exception on /user/bob [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'user' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-07 09:55:30,403 ERROR: Exception on /user/bob [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'user' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-07 10:01:26,791 ERROR: Exception on /user/bob [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'user' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-07 10:01:44,969 INFO: Microblog startup [in C:\Python\projects\CoreCracker\app\__init__.py:77]
2022-06-07 10:01:53,434 ERROR: Exception on /user/bob [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'user' did not return a valid response. The function either returned None or ended without a return statement.
