2022-07-11 10:16:24,978 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:17:32,712 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:46:18,961 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-07-11 10:47:20,950 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:47:55,425 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:50:57,385 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-07-11 10:51:11,860 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:52:40,106 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
