2022-07-11 09:56:09,018 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 09:57:14,571 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:01:56,815 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:03:43,094 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:05:55,626 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
2022-07-11 10:14:41,735 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 246, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 71, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 54, in uninUtilDirn
    intc_A, intc_B = parser.parsIntcItem(item['name'])   #получаем имена интерфейсов
  File "C:\Python\projects\CoreCracker\app\parser.py", line 86, in parsIntcItem
    return listIntc[0], listIntc[-1]
IndexError: list index out of range
