2022-09-03 23:16:34,510 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 168, in getTredSerhDays
    print(listPerdDays[cout - 1][0])
IndexError: list index out of range
2022-09-03 23:18:25,970 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 168, in getTredSerhDays
    else:
IndexError: list index out of range
2022-09-03 23:25:16,161 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 23:26:22,246 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 169, in getTredSerhDays
    if day - listPerdDays[cout - 1][0] > 2: listPerdDays.append([day])
IndexError: list index out of range
2022-09-03 23:33:45,343 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 23:34:21,476 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 169, in getTredSerhDays
    if day - listPerdDays[cout - 1][0] > 2: listPerdDays.append([day])
IndexError: list index out of range
2022-09-03 23:36:41,634 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 23:39:06,781 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 23:43:30,160 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 23:44:11,972 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 169, in getTredSerhDays
    print(day - listPerdDays[cout - 1][0])
IndexError: list index out of range
2022-09-03 23:46:47,667 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
