2022-09-03 23:47:31,665 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 169, in getTredSerhDays
    print(day, listPerdDays[cout - 1][0])
IndexError: list index out of range
2022-09-03 23:48:22,077 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-03 23:50:41,183 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:02:35,099 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:02:55,350 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 170, in getTredSerhDays
    listPerdDays[cout - 1][1] = listPerdDays[cout - 1][0] + 1
IndexError: list assignment index out of range
2022-09-04 00:04:40,122 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:11:34,864 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:12:34,680 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:17:42,213 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:20:18,334 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:23:04,422 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:26:44,456 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 169, in getTredSerhDays
    if day - listPerdDays[cout - 1][0] >= 2:  #если разница больше или равна 2
IndexError: list index out of range
2022-09-04 00:31:19,533 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:31:50,658 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 169, in getTredSerhDays
    if day - listPerdDays[cout - 1][0] >= 2:  #если разница больше или равна 2
IndexError: list index out of range
2022-09-04 00:37:00,132 INFO: Corecracker startup [in C:\Python\projects\CoreCracker\app\__init__.py:81]
2022-09-04 00:37:52,836 ERROR: Exception on /utilization_hosts [POST] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 245, in utilization_hosts
    zabxDirn = parser.parsHosts(hosts, instance)
  File "C:\Python\projects\CoreCracker\app\parser.py", line 48, in parsHosts
    zabxDirn = zabxmax.uninUtilDirn(zabxDirn, inst)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 114, in uninUtilDirn
    getTredAvrg2(dirn['listIntcItem'], zabx)
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 130, in getTredAvrg2
    listDays = getTredSerhDays(listItemIDOperStts, zabx)   #получаем список временных периодов, когда ни один из интерфейсов не падал
  File "C:\Python\projects\CoreCracker\app\zabxmax.py", line 169, in getTredSerhDays
    if day - listPerdDays[cout - 1][-1] >= 2:  #если разница больше или равна 2
IndexError: list index out of range
