2022-06-04 22:48:49,055 ERROR: Exception on /explore [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 126, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 13, in template
    {{% for error in form.post.errors %}}
jinja2.exceptions.TemplateSyntaxError: unexpected '%'
2022-06-04 22:52:30,486 INFO: Microblog startup [in C:\Python\projects\CoreCracker\app\__init__.py:77]
2022-06-06 18:21:00,343 INFO: Microblog startup [in C:\Python\projects\CoreCracker\app\__init__.py:77]
2022-06-06 18:21:55,168 ERROR: Exception on /explore [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 128, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Python\projects\CoreCracker\app\templates\base.html", line 40, in top-level template code
    {% block content %}
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 20, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-06-06 18:22:17,614 ERROR: Exception on /explore [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 128, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Python\projects\CoreCracker\app\templates\base.html", line 40, in top-level template code
    {% block content %}
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 20, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-06-06 18:27:23,592 ERROR: Exception on /explore [GET] [in C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Python\projects\CoreCracker\app\routes.py", line 128, in explore
    return render_template('index.html', title='Explore', posts=posts.items)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\projects\CoreCracker\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Python\projects\CoreCracker\app\templates\base.html", line 40, in top-level template code
    {% block content %}
  File "C:\Python\projects\CoreCracker\app\templates\index.html", line 20, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
